source 'https://rubygems.org'

gem 'rack', '~> 1.5.2'

gem 'grape'
gem 'json'

# Testing
gem 'rack-test', '~> 0.6.2', :group => [:test]
gem 'rake', '~> 10.1.1', :group => [:test]
gem 'rspec', '~> 2.14.1', :group => [:test]
